version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Zipping index-photos Lambda"
      - cd Lambda_functions/index-photos
      - zip -r ../../index-photos.zip .
      - cd ../../
      - echo "Zipping search-photos Lambda"
      - cd Lambda_functions/search-photos
      - zip -r ../../search-photos.zip .
      - cd ../../
artifacts:
  files:
    - index-photos.zip
    - search-photos.zip
