version: 0.2

phases:
  install:
    commands:
      - echo Installing AWS CLI...
      - pip install --upgrade awscli
  build:
    commands:
      # Prepare index-photos Lambda package
      - echo "Building index-photos Lambda package"
      - mkdir index-photos-deploy
      - cp -r lambdafunctions/index-photos/* index-photos-deploy/
      - cd index-photos-deploy
      - zip -r ../index-photos.zip .
      - cd ..

      # Prepare search-photos Lambda package
      - echo "Building search-photos Lambda package"
      - mkdir search-photos-deploy
      - cp -r lambdafunctions/search-photos/* search-photos-deploy/
      - cd search-photos-deploy
      - zip -r ../search-photos.zip .
      - cd ..
  post_build:
    commands:
      - echo Updating index-photos Lambda...
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://index-photos.zip
      - echo Updating search-photos Lambda...
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://search-photos.zip

artifacts:
  files:
    - index-photos.zip
    - search-photos.zip
